- name: load current inventory
  slurp:
    path: "{{ apollo_space_dir }}/.apollorc.yml"
  register: apollorc
  tags:
    - create

- name: extract the data
  set_fact:
    apollorc: "{{ apollorc['content'] | b64decode | from_yaml }}"
  tags:
    - create

- name: show data
  debug:
    var: apollorc
    verbosity: 1
  tags:
    - create

- name: update current inventory
  template:
    src: ".apollorc.yml.j2"
    dest: "{{ apollo_space_dir }}/.apollorc.yml"
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="
  tags:
    - create