- name: loading current inventory
  slurp:
    path: "{{ apollo_space_dir }}/.apollorc.yml"
  register: apollorc
  tags:
    - create

- name: extracting data
  set_fact:
    apollorc: "{{ apollorc['content'] | b64decode | from_yaml }}"
  tags:
    - create

- name: showing data
  debug:
    var: apollorc
    verbosity: 1
  tags:
    - create

- name: updating current inventory
  template:
    src: ".apollorc.yml.j2"
    dest: "{{ apollo_space_dir }}/.apollorc.yml"
  tags:
    - create