- name: creating server
  hcloud_server:
    name: "{{ blueprint['spec']['meta']['name'] + master_index|default(1)|string }}"
    server_type: "{{ blueprint['spec']['size'] }}"
    image: "{{ blueprint['spec']['image'] }}"
    location: "{{ blueprint['spec']['location'] }}"
    ssh_keys: "{{ lookup('env','SSH_KEYS', allow_undefined=false).split(',') }}"
    labels: "{{ blueprint['spec']['meta']['labels'] }}"
    api_token: "{{ lookup('env','HCLOUD_TOKEN', allow_undefined=false) }}"
    state: present
  register: server
  loop: "{{ range(1, blueprint['count'] + 1 )|list }}"
  loop_control:
    loop_var: master_index

- name: showing server
  debug:
    var: server
    verbosity: 1

- name: adding server to inventory
  add_host:
    groups: 
      - "{{ group }}"
      - cluster
    hostname: "{{ server.hcloud_server['name'] }}"
    ansible_host: "{{ server.hcloud_server['ipv4_address'] }}"
    ansible_user: "root"
    ansible_port: 22

- name: show inventory
  debug:
    var: hostvars
    verbosity: 1