---
- name: "checking conditions"
  hosts: localhost
  gather_facts: yes
  vars:
    apollo_runtime_version: "{{ lookup('env','APOLLO_VERSION') }}"
  tasks:
    - debug:
        var: hostvars['master1']
    - fail: 
        msg: "You're running {{ apollo_runtime_version }} but specified version {{ version }} in .apollorc.yml"
      when:
        - hostvars[inventory_hostname]['version'] != ''
        - apollo_runtime_version != hostvars[inventory_hostname]['version']
        - not lookup('env','APOLLO_FORCE')|bool

    - fail: 
        msg: "Deployment not needed because you've chosen 'docker' as provider. Run 'apollo bootstrap' to start your cluster."
      when:
        - hostvars[groups['master'][0]]['ansible_connection'] == 'docker'
  tags:
    - always
    - version

- name: "deploying"
  import_playbook: playbooks/deploy.yml
  tags:
    - deploy